### ISSUE TITLE
Versiyon kontrolü

### ISSUE THREAD

**Issue by onurozgurozkan** [Projekod/Bulutfon-WooCommerce-Eklentisi#2]
Benim şahsi görüşüm eklentinin versiyonu bir yerde yazmalı. Hata yeni versiyonu çıkınca kırmızı olup yeni bir versiyon var diye link verebilir.

Misal github üzerinden version.json parse edilip. Yeni sürüm kontrol edilebilir. Hatta changelog.md veya update.md gibi bir dosyaya link verilebilir.

Biz her ne kadar toplu duruyu yapsak bile eski kullanıcılar yeni versiyonlardan haberdar olmayabilir.

**Comment by aligundogdu** [comment]
Aynen, Final versiyonları düzenleyip öyle atalım

yeni major değişiklik olduğu sürece güncelleriz.
